### ISSUE TITLE
helix heisenberg theme text blinking

### ISSUE THREAD

**Issue by wellyton-xs** [IrishMaestro/heisenberg-helix-theme#1]
I don't know why this is happening, my terminal is konsole and I configure transparent settings in it and I choose heisenberg because transparency works. But when I write shell script, my comments flash? what is that? I don't know. Please help me because your theme is beautiful and matches the colors of my terminal

**Comment by irishmaestro** [comment]
Glad you enjoy the theme. This is a feature, not a bug.

https://www.wired.com/story/its-not-a-bug-its-a-feature/


To disable flashing comments, remove the `slow_blink` modifier on the comment line in the `heisenberg.toml` file.

E.g.

```toml
# Author: IrishMaestro <github.com/irishmaestro>

# Syntax highlighting
"type" = { fg = "crystal_blue" }
"type.builtin" = { fg = "crystal_blue" }
"constructor" = { fg = "barium_green" }
"constant" = { fg = "hazmat_yellow" }
"string" = { fg = "crystal_blue" }
"string.regexp" = { fg = "orange" }
"string.special" = { fg = "vapor_yellow" }
"comment" = { fg = "teddy_bear_pink", modifiers = ["italic"] }
"variable" = { fg = "element_green" }
"variable.parameter" = { fg = "hazmat_yellow" }
"label" = { fg = "vapor_yellow" }
"punctuation" = { fg = "barium_green" }
"keyword" = { fg = "barium_green" }
"keyword.control" = { fg = "barium_green" }
"keyword.directive" = { fg = "teddy_bear_pink" }
"operator" = { fg = "hazmat_yellow" }
"function" = { fg = "cash_green", modifiers = ["bold"] }
"tag" = { fg = "crystal_blue" }
"namespace" = { fg = "hazmat_yellow" }
"markup.heading" = { fg = "hazmat_yellow" }
"markup.list" = { fg = "vapor_yellow" }
"markup.raw.block" = { bg = "background", fg = "orange" }
"markup.link.url" = { fg = "crystal_blue" }
"markup.link.text" = { fg = "vapor_yellow" }
"markup.link.label" = { fg = "barium_green" }
"markup.quote" = { fg = "vapor_yellow" }
"diff.plus" = { fg = "cash_green" }
"diff.minus" = { fg = "chili_powder_red" }
"diff.delta" = { fg = "orange" }

# Interface
"ui.background" = { bg = "background" }
"ui.cursor" = { bg = "crystal_blue", fg = "background" }
"ui.cursor.match" = { fg = "hazmat_yellow" }
"ui.linenr" = { fg = "crystal_blue" }
"ui.linenr.selected" = { fg = "barium_green" }
"ui.statusline" = { fg = "crystal_blue", bg = "black" }
"ui.statusline.normal" = { fg = "crystal_blue", bg = "black" }
"ui.statusline.insert" = { fg = "barium_green", bg = "black"} 
"ui.statusline.select" = { fg = "hazmat_yellow", bg = "black" }
"ui.cursorline.primary" = { bg = "#041B0E" }
"ui.popup" = { fg = "crystal_blue", bg = "background" }
"ui.window" = { fg = "barium_green" }
"ui.help" = { fg = "crystal_blue", bg = "background"}
"ui.text" = { fg = "crystal_blue" }
"ui.text.focus" = { bg = "background", fg = "barium_green" }
"ui.text.info" = { fg = "crystal_blue" }
"ui.virtual.whitespace" = { fg = "#08341B" }
"ui.virtual.ruler" = { bg = "#041B0E" }
"ui.virtual.indent-guide" = { fg = "#08341B" }
"ui.menu" = { fg = "crystal_blue", bg = "background" }
"ui.menu.selected" = { bg = "hazmat_yellow", fg = "background" }
"ui.selection" = { bg = "#1B0334" }
"ui.selection.primary" = { bg = "desert_maroon" }
"warning" = { fg = "vapor_yellow" }
"error" = { fg = "chili_powder_red", modifiers = ["bold"] }
"info" = { fg = "crystal_blue", modifiers = ["bold"] }
"hint" = { fg = "crystal_blue", modifiers = ["bold"] }
"diagnostic"= { fg = "chili_powder_red", modifiers = ["underlined"] }
"diagnostic.info"= { fg = "crystal_blue", modifiers = ["underlined"] }
"diagnostic.warning"= { fg = "vapor_yellow", modifiers = ["underlined"] }
"diagnostic.error"= { fg = "chili_powder_red", modifiers = ["underlined"] }
"ui.bufferline" = { fg = "gray", bg = "background" }
"ui.bufferline.active" = { fg = "foreground", bg = "dark_gray" }

"special" = { fg = "cash_green" }

[palette]
background = "#000000"   
foreground = "#cccccc"
black = "#121212"
dark_gray = "#2d3640"
gray = "#5c6773"
orange = "#ff8f40"
barium_green = "#009669"
hazmat_yellow = "#f7b90c"
vapor_yellow = "#cecd19"
teddy_bear_pink = "#bd5173"
crystal_blue = "#32c9fa"
cash_green = "#00ff80"
element_green = "#186800"
desert_maroon = "#2B0C02"
chili_powder_red = "#c32101"
```
